media:
  path: public
  public_path: /
content:
  - name: business
    label: Business Config
    path: business.json
    type: file
    icon: building
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
        options:
          maxLenght: 170
      - name: site
        label: URL Website
        description: "Example: https://website.com"
        type: string
        required: true
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: robots
        label: Robots
        type: object
        hidden: true
        fields:
          - name: index
            label: No Index
            type: boolean
            default: false
          - name: follow
            label: No Follow
            type: boolean
            default: false
      - name: openGraph
        label: Open Graph
        description: Image size must be 1200 x 630 px and must weigh less than 1M
        required: true
        type: image
        options:
          extensions: [jpg, jpeg, png]
      - name: contact
        label: Contact
        type: object
        fields:
          - name: tel
            label: Phone
            type: object
            fields:
              - name: ext
                description: "Example: 502"
                label: Extension
                type: number
                required: true
                default: 502
              - name: number
                label: Number
                type: number
                required: true
          - name: whatsapp
            label: WhatsApp
            type: object
            fields:
              - name: ext
                description: "Example: 502"
                label: Extension
                type: number
                required: false
                default: 502
              - name: number
                label: Number
                type: number
                required: false
          - name: email
            label: Email
            type: string
            required: true
            pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$
      - name: address
        label: Address
        type: object
        fields:
          - name: location
            label: Location
            type: string
            required: true
      - name: googleTagManager
        label: Google Tag Manager
        type: object
        fields:
          - name: id
            label: ID
            type: string
      - name: social
        label: Social Media
        type: object
        fields:
          - name: facebook
            label: Facebook
            type: string
          - name: instagram
            label: Instagram
            type: string
          - name: tiktok
            label: TikTok
            type: string
          - name: youtube
            label: YouTube
            type: string
          - name: linkedin
            label: LinkedIn
            type: string
          - name: twitter
            label: Twitter
            type: string
      - name: configuracion
        label: Configuración
        type: object
        fields:
          - name: emailSender
            label: Remitente del correo (Email Sender)
            type: string
            required: false
            pattern: ^[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}$
          - name: bccEmail
            label: Correos en copia oculta (BCC)
            type: string
            list: true
            pattern: ^[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}$
            required: false
          - name: resendToCompany
            label: Reenviar a la empresa
            description: "Si es verdadero, el correo también será enviado a la dirección de correo de la empresa"
            type: boolean
            default: true

  - name: products
    label: Productos
    type: collection
    path: src/content/products
    format: json
    icon: shopping-bag
    fields:
      - name: name
        label: Nombre del Producto
        type: string
        description: "Ej.  Calcetines de algodón"
        required: true
      - name: slug
        label: Slug (URL)
        type: string
        description: "Ej.  calcetines-de-algodon"
        required: true
      - name: price
        label: Precio
        description: "Ej.  250"
        type: number
        required: true
      - name: tag
        label: Etiqueta o categoría
        type: string
        description: "Ej. women, destacado, running, gym, algodón, blanco"
      - name: color
        label: Color del producto
        type: string
        description: "Ej. blanco, negro, beige"
      - name: size
        label: Tallas Disponibles
        type: string
        description: "Ej. unitalla"
        list: true
        required: true
      - name: description
        label: Descripción
        type: rich-text
      - name: moreDetails
        label: Más detalles del producto
        type: object
        list: true
        fields:
          - name: title
            label: Título
            type: string
            description: "Ej. Durabilidad extrema"
            required: true
          - name: description
            label: Descripción
            type: string
            description: "Ej.  Refuerzos de triple hilo en talón y punta para resistir el desgaste del uso diario y el asfalto."
            required: true
      - name: img
        label: Imagen Principal
        type: image
        required: true
        options:
          extensions: [jpg, jpeg, png]
      - name: gallery
        label: Galería de Imágenes
        type: image
        list: true
        options:
          extensions: [jpg, jpeg, png]
